language: python
python:
- '3.6.6'

install:
- pip install pipenv
- SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev
- pipenv run airflow initdb
script:
- pipenv run pylint tulflow -E
- pipenv run nosetests
after_success:
- true
before_deploy:
- true
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: cmharlow
  password:
    secure: aDzVKNqrAMrYE5OqY/iCzLCCqyJFYycSJMR6LeSp8jCLXDR5aU4biobPTSNTsn+flnOzXw1JL1YFBvIDQazK9roTTrGulyOpDdFxOsqkijfttR4IfH8FsegEqKV+SMfit+Uj8tgdZ7vY13tphRAXaiNFYGkwrUIgWNECPWoRtC6pI88yqdP8U41eFQ1uTEfAcUZyW//CYtV6QLkMrrEBUbhumptbI6tIlBq2WJ/BvnD8QfzpVrsgbBSekJDpjm2M03zGryUSF345Mzp4RrLPQXZnZxXf776s20MVmdVvPzLZHPOKSwWc1Xd+DJCX2Y4gV1F5ZyD5WnfdaiSdONPo8jme3mI3usVslPS9MV5NQd3whiJ9Y58/YbtWgViZH9r1D5scTaJauvA+k0D1SW1zvRzSgy3uzKnFuwLbP9m8YY1cBPY78Ms50BdHK0Sk5m6x8p8o9YsBzS8BrDAd6jfP9F/iKZvRNQ9X95jbABrOt2aHRHBU0n1fjPaW1/2oZOVOM16eEB6/y22HZUlTC6q9QE19vxEcRjoV2b3UZU8ebUnoGChJmufpQi9ca2mlfx5pGs95JR09Kqs5Oxo3qAZiAi9AQk4UPdadK6IH3kvUgCjWGvGIelZ3iE6NqPExQPH3nePyYAO4dJnBzODY6V1xMsAQK0OPITzANOKxGOkpVg4=
  on:
    tags: true
    branch:
      - /^v(\d+)\.(\d+)(\.\d+)?$/
notifications:
  slack:
    rooms:
      - secure: SDncKtH2PvP4q1sJDL/m0oJNaE78Ye0S2yQGmVOE71/a0ShzKCzt+Pa6SaklKspdcrD7D1AtgwJGwkQhxaqXtDDRI4WyYjCIi2I7VHy5drnzEddtpAi4mPedoqEC8m6lQbsmKewQFq5uFCQYetp7YHV675B3noOnGbWw0t3s0UVn17XV7G2zk3a6l4H9Rj7dM9eSbcSTl+vWoHA93ZoQpId278ZV4cTbL0lXvhAueTM1FCKAZxArHMRa3UA4ocDsO9tqiKK96Gf4qzcVzYAhc9tW2Tx/9wjvsAAKxRpdWjQ5n1oMX+oAhSIocxn9p3ye8GZ5OwgB3acigPcKt8foc6SuYrX2Ppu/s3BdJz9AK/fiRdqtpEu1PiQAbsAdhatGh2OolvaymR9LQ4NVLk+xvctUANS5TeFEnIfEl73SxPwh844PznwKiTFSvN/XAd+39R1BNHJopGgJfzaObODgI8uKtqQA4UPVxyuB3PfWAqUGJKRecqu9yaGnQhqqZdyL+o4GXqWBdXaRXwdRHtmwpbFa71RnjyWttOIMKxQhKTVhOtcAuuu3qwj+Z7q7hrxMwkL/Xq4gJ5jbfzcWbN/Tik47YXLppIOYT+57i1QeQAokHarE5/0/RhBMwn9mWqcP77IE8h+FAMaVtdOQbbULYGluhpHgENXL9f/FIDEZp/A=
    on_success: always
    on_failure: always
