version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
          SLUGIFY_USES_TEXT_UNIDECODE: yes
    steps:
      - checkout
      - run: git submodule init; git submodule update
      - run:
          name: 'Install Dependencies'
          command: |
            SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev
      - run:
           command: pipenv run airflow db migrate
           name: Migrate Airflow Database
      - run:
          name: 'Check Airflow Constraints'
          command: |
            make compare-dependencies
      - run:
          name: 'Run Pylint'
          command: |
            make lint
      - run:
          name: 'Run Pytest'
          command: |
            make test

  build-and-deploy:
    docker:
      - image: cimg/python:3.12.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
          SLUGIFY_USES_TEXT_UNIDECODE: yes
    steps:
      - checkout
      - run:
          name: Verify git tag vs. version.
          command: |
            pip install --user twine
            python3 -m verify_version
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create package
          command: |
            #install the build tool
            pip install build
            # create a source distribution and a wheel
            python -m build
      - run:
          name: Upload to pypi
          command: python3 -m twine upload dist/*


workflows:
  main:
    jobs:
      - build-and-test
      - build-and-deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(\d+)\.(\d+)(\.\d+)?$/
