version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
          SLUGIFY_USES_TEXT_UNIDECODE: yes
    steps:
      - checkout
      - python/install-packages:
          args: --dev
          pkg-manager: pipenv
      - run:
          command: pipenv run airflow initdb
          name: Init Airflow
      - run:
          command: pipenv run pylint tulflow -E
          name: Lint
      - run:
          command: pipenv run nosetests
          name: Test

  build-and-deploy:
    docker:
      - image: circleci/python:3.6.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
          SLUGIFY_USES_TEXT_UNIDECODE: yes
    steps:
      - checkout
      - python/install-packages:
          args: twine
      - run:
          name: Verify git tag vs. version
          command: python3 setup.py verify
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create package
          command: |
            # create a source distribution
            python3 setup.py sdist
            # create a wheel
            python3 setup.py bdist_wheel
      - run:
          name: Upload to pypi
          command: python3  -m twine upload --repository tulflow dist/*


workflows:
  main:
    jobs:
      - build-and-test
      - build-and-deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(\d+)\.(\d+)(\.\d+)?$/
